### ISSUE TITLE
Crash during connect call

### ISSUE THREAD

**Issue by sabolcik** [kdschlosser/MiCasaVerde_Vera#1]
This looks like a great library.  Impressive that you are actively building the capabilities and device list on the fly.  I'm very interested in creating more complicated control of my vera via this library.  

I'm relearning python after being away for many years so I apologize in advance if this is pilot error.  I load the package in python, do a dir on the module list and successfully discover my Vera's IP address.  But when I go to connect I get an error.  The steps I performed in an interactive python session are shown below.  Any ideas?  I'm wondering if it might be caused by some dead devices I have not been able to remove from my Vera.  Any suggestions or thoughts?

Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import micasaverde_vera
>>> dir(micasaverde_vera)
['ImportOverride', 'VeraBuildError', 'VeraError', 'VeraImportError', 'VeraNotFoundError', 'VeraNotImplementedError', 'VeraUnsupportedByDevice', '_BUILD_PATH', '_UNWANTED_ITEMS', '_VERSION', '_VeraBase', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__version__', 'build_files', 'build_templates', 'connect', 'constants', 'deepcopy', 'discover', 'import_override', 'init_core', 'os', 'print_function', 'rebuild_files', 'sys', 'threading', 'update_files', 'utils', 'vera_build', 'vera_exception']
>>> ip = micasaverde_vera.discover()
>>> ip
'192.168.86.62'
>>> instance = micasaverde_vera.connect(ip)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "micasaverde_vera/__init__.py", line 332, in connect
    return __Vera(ip_address)
  File "micasaverde_vera/__init__.py", line 293, in __init__
    _VeraBase.__init__(self, ip_address)
  File "micasaverde_vera/__init__.py", line 422, in __init__
    self.__update(self.scenes, 'scenes', data)
  File "micasaverde_vera/__init__.py", line 465, in __update
    obj.update_node(data.pop(key, None), True)
  File "micasaverde_vera/scenes.py", line 102, in update_node
    found_scene = Scene(self, **scene)
TypeError: __init__() got an unexpected keyword argument 'onDashboard'

**Comment by kdschlosser** [comment]
ok this is an easy fix.. There are things in which i didn't take into account. Very hard to get everything in there out of the gate. It appears that your scenes have an extra parameter "onDashboard". I am going to have to use **kwargs in the constructor for as scene.

I will let you know when I have updated the code

**Comment by kdschlosser** [comment]
I have updated the code. i didn't give any access to the onDashboard parameter. But it should get the library up and running for ya.

**Comment by kdschlosser** [comment]
Also any dead devices on your vera you will be able to remove them with this library.

**Comment by sabolcik** [comment]
Kevin:

Wow.  Thanks for the quick response.  I'm excited to try your library.

Will install the update tonight and give it a whirl.

-Ross

**Comment by sabolcik** [comment]
Loaded up the latest code and got the following 

>>> import micasaverde_vera
>>> vera = micasaverde_vera.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "micasaverde_vera/__init__.py", line 332, in connect
    return __Vera(ip_address)
  File "micasaverde_vera/__init__.py", line 293, in __init__
    _VeraBase.__init__(self, ip_address)
  File "micasaverde_vera/__init__.py", line 422, in __init__
    self.__update(self.scenes, 'scenes', data)
  File "micasaverde_vera/__init__.py", line 465, in __update
    obj.update_node(data.pop(key, None), True)
  File "micasaverde_vera/scenes.py", line 102, in update_node
    found_scene = Scene(self, **scene)
  File "micasaverde_vera/scenes.py", line 158, in __init__
    self.groups = Groups(self, groups)
  File "micasaverde_vera/scenes.py", line 539, in __init__
    self.groups += [Group(self, scene, len(self.groups) + 1, **group)]
  File "micasaverde_vera/scenes.py", line 586, in __init__
    self.actions = Actions(self, scene, actions)
  File "micasaverde_vera/scenes.py", line 350, in __init__
    Action(self, scene, **action) for action in actions
  File "micasaverde_vera/scenes.py", line 350, in <genexpr>
    Action(self, scene, **action) for action in actions
  File "micasaverde_vera/scenes.py", line 424, in __init__
    self.arguments = Arguments(self, arguments)
  File "micasaverde_vera/scenes.py", line 994, in __init__
    Argument(self, **argument) for argument in arguments
  File "micasaverde_vera/scenes.py", line 994, in <genexpr>
    Argument(self, **argument) for argument in arguments
  File "micasaverde_vera/scenes.py", line 1080, in __init__
    Notify(self, self.build_event() + '.created')
  File "micasaverde_vera/scenes.py", line 1086, in build_event
    event = self.id
AttributeError: 'Argument' object has no attribute 'id'

I noticed that I used the autodiscover feature when this crash occured.  My prior crash occurred when passing an explicit IP address.  So I reran with an explicit Vera IP address and got the same crash.

Any ideas?  

With regards to the onDashboard attribute that crashed earlier it appears that this variable *doesn't* exist in the device attributes until *after* you use the star on a given device to indicate it as a node you want to include on the dashboard tab in UI7.  Once created the attribute persists even if you remove the device from the dashboard.  Devices that have never been added to the dashboard tab do not have the attribute.  I upgrade from UI5 recently so I thought maybe any devices added to the Vera after UI7 would have the attribute by default but I have verified that they don't.

**Comment by kdschlosser** [comment]
To be honest with ya. I never really finished up the scenes section of this library. This is because the main project I am involved in is called EventGhost and is a Home Automation program for Windows. I can see you use linux so this would not be of much help. But I made a plugin for EventGhost that has the ability to communicate with the Vera. So anyone that uses it is able to "offload" all of their scenes and have EventGhost take care of that end of things.

Then through my various tinkerings I managed to get openzwave to compile and run with Python 2.7 and since then i have not done any more work with this as I am not using my Vera anymore.

I will take a look at this error. It should be a pretty simple one to figure out as it has to deal with an internal event thing.

**Comment by kdschlosser** [comment]
I just wanted to let you know we could be working through some problems because i never finished this thing 100% But I am willing to work on it if you are willing to endure.

I updated the code so the latest traceback should be fixed.

**Comment by sabolcik** [comment]
Thanks again for your help.  Totally understand the Beta nature of the code
and appreciate your willingness to tweak it.  I wound up on a linux box
after trying, unsuccessfully, to get SSL certifcates and nginx port
forwarding working on a windows machine.  My primary use case for the linux
box is as a server for custom alexa skills since I didn't want to learn
lambda coding to run the skills on AWS.  Regardless your other project
sounds interesting and I might check that out as an option.

I'll load this drop tonight and let you know how it goes.  I think once the
initialization code is working I should be good to go.

**Comment by sabolcik** [comment]
Looks like continued progress but now there is a crash with the timers.  I can try to look at your code to see if I can make sense of it.  I really only need to control the devices and get their status not call scenes or timers.  Not sure if i can figure out how to disable that part of the code or if this is another easy fix.

>>> import micasaverde_vera
>>> ip_address = micasaverde_vera.discover()
>>> ip_address
'192.168.86.62'
>>> instance = micasaverde_vera.connect(ip_address)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "micasaverde_vera/__init__.py", line 332, in connect
    return __Vera(ip_address)
  File "micasaverde_vera/__init__.py", line 293, in __init__
    _VeraBase.__init__(self, ip_address)
  File "micasaverde_vera/__init__.py", line 422, in __init__
    self.__update(self.scenes, 'scenes', data)
  File "micasaverde_vera/__init__.py", line 465, in __update
    obj.update_node(data.pop(key, None), True)
  File "micasaverde_vera/scenes.py", line 102, in update_node
    found_scene = Scene(self, **scene)
  File "micasaverde_vera/scenes.py", line 160, in __init__
    self.timers = Timers(self, timers)
  File "micasaverde_vera/scenes.py", line 822, in __init__
    self.timers = list(Timer(self, scene, **timer) for timer in timers)
  File "micasaverde_vera/scenes.py", line 822, in <genexpr>
    self.timers = list(Timer(self, scene, **timer) for timer in timers)
TypeError: __init__() got an unexpected keyword argument 'interval'

**Comment by sabolcik** [comment]
So I played around in the code and found that the interval parameter was trying to be passed to both the constructor for Timer and one other class in scenes.  I just added the variable to the constructors with a default value.  I was able to get the connect command to work.   Yeah!

Once I got connect to work I was able to take a few devices and control them.  Yeah again.

I have some sensor nodes that I am trying to poll for my application.  The good news is that I can see the variables I am interested in via the get_variables() function.  So for example I can read the temperature from a 4 way sensor.  What I can't figure out how to do is to update those variables to get the most recent readings.

Not sure if you have any example code that shows that operation.  The update command on a device seems to take a list of parameters I can't grok the meaning of.  Not sure if you have any examples of using your library to repopulate the variables after a poll command to get the most recent readings.

At least I am connecting now.  I apologize that my python skills are rusty and not being able to grok the parameters for these calls.

**Comment by kdschlosser** [comment]
you have to start up the polling loop. and from there it will automatically update every single piece of data gotten from the Vera every n milliseconds. I grab most of the data via JSON from the Vera as this is to lessen the overhead on the Vera. Having the Vera convert the data from JSON to XML is very expensive.

The update parameter is used internally and each of the different objects requires a different set of data coming into it. so it has to populate down the tree of objects.

There is also a built in event callback system. So you need not monitor for changes. it does this internally as it updates the information. if the information has changed it will trigger the event callback notification system.



This is going to be a little long winded on how to use the system. 

to start the polling loop.

    import micasaverde_vera

    vera = micasaverde_vera.connect('192.168.1.1')
    vera.start_polling(0.2) # 0.2 = every 200 milliseconds

NOTE: If you plan on using the Vera UI then you will have to tinker with the interval setting. the lower the number the faster it is going to ask for updates. This is going to have a HUGE impact on the speed in which the Vera UI responds. if you do not plan on using the Vera UI then you can set it to 0.1 if you want. Setting the number lower then 0.1 will not give you faster updates.

The code below is an example of how the polling system works.  in this example you will be able to run code while the script is running. so if you wanted to tell a device to do something and watch the event unfold in front of you. you are able to.

IP_ADDRESS = '192.168.1.2'
DEVICE_NUMBER = None
SHOW_ALL_EVENTS = True

`
import micasaverde_vera

def test_callback(event):
    if SHOW_ALL_EVENTS:
        print event.event

    split_event = event.event.split('.')

    def check_event():

        if split_event[-1] == 'changed':
            print
            print'--------------------------------------------'
            print event.event
            attr_name = split_event[-2:][0]
            try:
                print event.name
            except AttributeError:
                print 'NO NAME'
            print attr_name, '=', getattr(event, attr_name)
            print'--------------------------------------------'
            print

    if split_event[0] == 'device':
        if split_event[1] == str(DEVICE_NUMBER):
            check_event()

    elif split_event[0] == 'room':
        check_event()

vera = micasaverde_vera.connect(IP_ADDRESS)
event_handler = vera.bind('*', test_callback)
vera.start_polling(0.2)

while True:
    command = [
        raw_input('key in commands here. the last line must be RUN\n\n')]
    while command[-1] != 'RUN' and not command[-1].endswith('RUN'):
        command += [raw_input('')]
    command = '\n'.join(command)[:-3]

    try:
        exec command
    except:
        import traceback
        traceback.print_exc()
`

The event system is broken into parts. If you leave SHOW_ALL_EVENTS set to True it will display all of the event names that take place.

The structure of the event name is separated by a "."
a device event starts with "devices"
a room event starts with "rooms"
and so on and so forth

I used the ID of the objects on the vera in the event to identify them. this is because those remain a constant.

so if you have a room named "Kitchen" you will gets it's id and use that in the event. so in this example we will say that the id is 5.

rooms.5

this alone will not do anything we need to specify what events we want for rooms,5
if you use rooms.5.* you will get every event that is generated for that room. if you use rooms.* you will get all events for all rooms.

if you only want to get events for values that have changed. then you would use rooms.5.*.changed
once you have determined what events you want to receive callbacks for you will bind a callback function to the event by calling vera.bind("rooms.5.*.changed", some_callback)

You need to have one parameter for the callback and that is to receive the event object. the event object is a gateway to the actual item that caused the event so any attributes/methods that are available for the object that caused the event are also available in the event object it's self.

You can also unbind (stop receiving events) from the event object directly or you can use 
vera.unbind(event_object)

event_object is the object that is returned when you initially called vera.bind

the vera has a very large amount of information to it. I tried to make the event system as easy to use as possible. you can bind to events like this  *.loadLevelStatus..changed and this should report all dimmer switch changes. In the example above i simply used a * and nothing else. this spits out every single event that can take place. I put into place a filter for the event as an example.

**Comment by sabolcik** [comment]
Kevin:

Thanks again for the great support.  I'm not entirely sure about the
etiquette for github so if this discussion is better handled on email let
me know.

Great to hear that the system can be setup to run event handlers.  That is
fantastic.  Understood about the polling interval impacting UI
performance.  Even when running polling on the Vera UI I have seen it
impact performance as the sensor nodes I was polling took a long time to
respond tying up the UI.

One additional question.  Some node will send asynchronous events back to
the Vera.  For example the energy monitoring plugs have the ability to
switch on/off but also report the power being drawn through the plug.
These devices can be configured to send an event to the Vera on a state
change > x Watts.  My understanding is that this ability removes the need
to do a synchronous poll from the Vera as you get an Asynchronous push from
the node.  Is there a mechanism in your library to get detect these events
and update the associated variable?  That would be useful for energy
monitoring and also security sensors being tripped.

So in your example above:

"if you only want to get events for values that have changed. then you
would use rooms.5.
*.changedonce you have determined what events you want to receive callbacks
for you will bind a callback function to the event by calling
vera.bind("rooms.5.*.changed", some_callback)"

If I had one of these asynchronous events I described above would I still
receive it even if I set the vera.start_polling() interval to a large
number or didn't even call the start_polling() command?

**Comment by kdschlosser** [comment]
ok the internal vera polling is quite different then the polling that is done from this library.

The polling internal to the vera is the vera collecting data from the devices. so having the device report changes would eliminate the need to have the vera poll the devices. 

But we still need a means to update the data that is in the library. so we have to ask the Vera for it. The Vera has a central "database" or JSON file that contains all of the information it has stored. I ask the Vera for the whole file. I do this because then the Vera has to do very little or even possibly no parsing of that file. This is to reduce the amount of impact on the Vera.

When i state the polling speed has a performance impact on the Vera UI. when set to 0.1 seconds  for example you may experience load times for pages and how long it takes the Vera to update the UI if something changes will increase. Increase means maybe an extra 2 seconds. The Vera is only able to do a single thing at a time. I do not think it has the ability to run multiple threads and it doesn't not have multiple cores (unless running a new Vera) because of this when the Vera polls a device it sits there and waits for an answer and does nothing else in the mean time. You will see a far greater impact in the UI from that then from this library asking the Vera for data.

ok So the events. using the Kitchen again as an example. If you want to show an event for when you change the name for the kitchen.

    def callback(event):
        print 'Room Name Changed: id={0}, name={1}'.format(event.id, event.name)

    vera.bind('rooms.5.name.changed', callback)

The above will only get run if the name for room 5 changes.

    def callback(event):
        print 'Room Name Changed: id={0}, name={1}'.format(event.id, event.name)

    vera.bind('rooms.*.name.changed', callback)

The above will get triggered if any room name gets changed.

There are 2 event types.
changed
added
removed

added and removed occurs for things like device, rooms, installed_plugins. (if a new plugin gets installed the library will automatically go and retrieve the plugin source files from the Vera and build python versions of them)

The changed event takes place when a property or attribute changes.

I did however forget to mention this.. for devices and a couple of other things the event will contain the service that the attribute or property belongs to. Because of how the Vera is set up it allows for multiple variables with the same name for a single device. This is because it stores the variable name in the actual service. 

Here is an example. if you take the Virtual Switch plugin and install it. then go into the advanced settings it gives you the ability to add variables. the virtual switch uses the BinaryLight1 service and it already has a variable by the name of state. but if you create a new variable with the name of state that new one gets stored in a completely different service, so now you can have 2 completely different events with the same variable name for the same device. so I had to come up with a means to identify who is what.

Run the script i posted in a previous post and it will show you the event structure. any of the items between the "." can be replaced with a * the start is a wildcard so if you want to watch all devices for a specific variable change. you can. or if you want to watch a specific device for all variable changes you can. Or if you want a specific device with a specific variable that can be done as well.

**Comment by kdschlosser** [comment]
If you want to have this library update it's information you have to start the polling. the interval all depends on how long you are willing to wait for the library to reflect the same information as the Vera it's self. 

I used my Vera for lighting. so as you can imagine i wanted to know right away if something changed. But if i was only going to use it for weather information and didn't care how fast the data would be updated i would set it to a much higher interval.

**Comment by sabolcik** [comment]
Keith:

Thanks for the feedback and great examples.  I was able to setup a polling loop and verified that the variables for the nodes I snooped were getting updated.  I'll start working on my application and playing around with the callback functions..

Great library that I look forward to using with my ongoing automation projects.

**Comment by kdschlosser** [comment]
No worries m8, If there is anything you need to have changed or if you happen across some kind of a bug or I missed adding something let me know.

**Comment by sabolcik** [comment]
There is one minor error in the event callback example:

def test_callback(event):
    if SHOW_ALL_EVENTS:
        print event.event

    split_event = event.event.split('.')

    def check_event():
        if split_event[-1] == 'changed':
            print
            print '--------------------------------------------'
            print event.event
            attr_name = split_event[-2:][0]
            try:
                print event.name
            except AttributeError:
                print 'NO NAME'
            print attr_name, '=', getattr(event, attr_name)
            print'--------------------------------------------'
            print

    **if split_event[0] == 'device': <- needs to be 'devices'**
        if split_event[1] == str(DEVICE_NUMBER):
            check_event()

    elif split_event[0] == 'room':
        check_event()

**Comment by kdschlosser** [comment]
woooops. missed a letter there. nice catch
